# Generated by Django 5.0 on 2023-12-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('mobile', models.CharField(max_length=15)),
                ('mobile2', models.CharField(max_length=15)),
                ('company', models.CharField(max_length=255)),
                ('rating', models.IntegerField(default=8)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='customers_c_name_f018e2_idx'), models.Index(fields=['mobile'], name='customers_c_mobile_e14eb1_idx'), models.Index(fields=['mobile2'], name='customers_c_mobile2_96e898_idx'), models.Index(fields=['company'], name='customers_c_company_b97478_idx')],
                'unique_together': {('name', 'mobile')},
            },
        ),
    ]
